# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('monto_anual_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_enero_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_febrero_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_marzo_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_abril_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_mayo_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_junio_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_julio_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_agosto_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_seotiembre_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_octubre_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_noviembre_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_diciembre_Autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('actividad', models.TextField()),
                ('meta', models.IntegerField()),
                ('unidad_de_medida', models.CharField(max_length=50)),
                ('fuente_de_financiamiento', models.IntegerField(choices=[(1, 'Federal'), (2, 'Estatal'), (3, 'Propios')])),
                ('beneficiarios', models.TextField()),
                ('oficio_de_autorizacion', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPresupuestal.Programa'),
        ),
    ]
