# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='monto_diciembre_Autorizado',
            new_name='monto_diciembre_autorizado',
        ),
    ]
