# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0002_auto_20161110_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='monto_seotiembre_autorizado',
            new_name='monto_septiembre_autorizado',
        ),
    ]
