# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0002_auto_20161206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_ejercido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_modificado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_por_ejercer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
