# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0003_auto_20161110_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programa',
            new_name='Proyecto',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='programa',
            new_name='proyecto',
        ),
    ]
