# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0004_auto_20161206_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='monto_anual_autorizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
