# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0004_auto_20161111_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Programa',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='proyecto',
            new_name='programa',
        ),
    ]
