# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0005_auto_20161111_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='capitulo',
            field=models.CharField(blank=True, choices=[(1000, '3000 - Servicios personales'), (2000, '2000 - Materiales y suministros'), (3000, '3000 - Servicios generales'), (4000, '4000 - Servicios generales')], max_length=50, null=True),
        ),
    ]
