# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0007_auto_20161111_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='monto_enero_ampliacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='capitulo',
            field=models.IntegerField(blank=True, choices=[(1000, '1000 - Servicios personales'), (2000, '2000 - Materiales y suministros'), (3000, '3000 - Servicios generales'), (4000, '4000 - Servicios generales')], null=True),
        ),
    ]
