# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0008_auto_20161114_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='monto_enero_reduccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
