# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0009_partida_monto_enero_reduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='monto_abril_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_abril_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_agosto_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_agosto_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_diciembre_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_diciembre_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_febrero_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_febrero_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_julio_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_julio_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_junio_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_junio_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_marzo_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_marzo_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_mayo_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_mayo_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_noviembre_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_noviembre_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_octubre_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_octubre_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_semtiembre_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_septiembre_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_enero_ampliacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='partida',
            name='monto_enero_reduccion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
