# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0010_auto_20161114_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='monto_semtiembre_reduccion',
            new_name='monto_septiembre_reduccion',
        ),
    ]
