# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0011_auto_20161209_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='codigo',
            field=models.IntegerField(choices=[(1000, '1000 - SERVICIOS PERSONALES'), (2000, '2000 - MATERIALES Y SUMINISTROS'), (3000, '3000 - SERVICIOS GENERALES'), (4000, '4000 - TRANSFERENCIAS, ASIGNACIONES, SUBSIDIOS Y OTRAS AYUDAS'), (5000, '5000 - BIENES MUEBLES, INMUEBLES E INTANGIBLES'), (6000, '6000 - INVERSIÓN PÚBLICA'), (7000, '7000 - INVERSIONES FINANCIERAS Y OTRAS PROVISIONES'), (8000, '8000 - PARTICIPACIONES Y APORTACIONES'), (9000, '9000 - DEUDA PÚBLICA')]),
        ),
    ]
