# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0011_auto_20161114_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='monto_enero_ejercido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
