# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0012_auto_20161210_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='pp',
            field=models.FloatField(default=0),
        ),
    ]
