# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0013_programa_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='pp',
            field=models.FloatField(null=True),
        ),
    ]
