# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0014_auto_20161213_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='pp',
            field=models.FloatField(default=0),
        ),
    ]
