# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal', '0017_auto_20161213_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='pp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
