# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_profesional', models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('Tecnico', 'Tecnico'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.')], max_length=30, null=True)),
                ('puesto', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('banco', models.CharField(choices=[('BBVA Bancomer', 'BBVA Bancomer'), ('Santander', 'Santander'), ('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('', 'Ninguno'), ('Inbursa', 'Inbursa'), ('American Express', 'American Express'), ('Banamex', 'Banamex'), ('HSBC', 'HSBC')], max_length=30)),
                ('cta_bancaria', models.CharField(blank=True, max_length=16, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Interno'), (2, 'Proveedor')])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
