# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('Banamex', 'Banamex'), ('BBVA Bancomer', 'BBVA Bancomer'), ('', 'Ninguno'), ('Inbursa', 'Inbursa'), ('American Express', 'American Express'), ('HSBC', 'HSBC'), ('Santander', 'Santander'), ('ScotiaBank Inverlat', 'ScotiaBank Inverlat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('Tecnico', 'Tecnico')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Proveedor'), (1, 'Interno')]),
        ),
    ]
