# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161215_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('Santander', 'Santander'), ('American Express', 'American Express'), ('HSBC', 'HSBC'), ('Banamex', 'Banamex'), ('BBVA Bancomer', 'BBVA Bancomer'), ('', 'Ninguno'), ('Inbursa', 'Inbursa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Tecnico', 'Tecnico'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.')], max_length=30, null=True),
        ),
    ]
