# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161215_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('BBVA Bancomer', 'BBVA Bancomer'), ('Banamex', 'Banamex'), ('Santander', 'Santander'), ('American Express', 'American Express'), ('Inbursa', 'Inbursa'), ('', 'Ninguno'), ('HSBC', 'HSBC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('Tecnico', 'Tecnico'), ('Lic.', 'Lic.')], max_length=30, null=True),
        ),
    ]
