# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161215_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('American Express', 'American Express'), ('BBVA Bancomer', 'BBVA Bancomer'), ('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('HSBC', 'HSBC'), ('Santander', 'Santander'), ('', 'Ninguno'), ('Inbursa', 'Inbursa'), ('Banamex', 'Banamex')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tecnico', 'Tecnico'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.')], max_length=30, null=True),
        ),
    ]
