# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170111_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Area'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('American Express', 'American Express'), ('Banamex', 'Banamex'), ('BBVA Bancomer', 'BBVA Bancomer'), ('Inbursa', 'Inbursa'), ('Santander', 'Santander'), ('HSBC', 'HSBC'), ('', 'Ninguno')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tecnico', 'Tecnico'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Interno'), (2, 'Proveedor')]),
        ),
    ]
