# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170124_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('Inbursa', 'Inbursa'), ('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('Banamex', 'Banamex'), ('BBVA Bancomer', 'BBVA Bancomer'), ('Santander', 'Santander'), ('HSBC', 'HSBC'), ('American Express', 'American Express'), ('', 'Ninguno')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Tecnico', 'Tecnico'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.')], max_length=30, null=True),
        ),
    ]
