# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170124_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Departamento',
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='area',
            new_name='departamento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.CharField(choices=[('ScotiaBank Inverlat', 'ScotiaBank Inverlat'), ('Santander', 'Santander'), ('Inbursa', 'Inbursa'), ('HSBC', 'HSBC'), ('', 'Ninguno'), ('American Express', 'American Express'), ('Banamex', 'Banamex'), ('BBVA Bancomer', 'BBVA Bancomer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tecnico', 'Tecnico'), ('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.')], max_length=30, null=True),
        ),
    ]
