# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170124_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Banco'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Tecnico', 'Tecnico'), ('Ing.', 'Ing.'), ('Lic.', 'Lic.')], max_length=30, null=True),
        ),
    ]
