# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170124_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Mtro(a).', 'Mtro(a).'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Tecnico', 'Tecnico')], max_length=30, null=True),
        ),
    ]
