# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170126_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Lic.', 'Lic.'), ('Tecnico', 'Tecnico'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.')], max_length=30, null=True),
        ),
    ]
