# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170126_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Tecnico', 'Tecnico'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.')], max_length=30, null=True),
        ),
    ]
