# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170126_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Tecnico', 'Tecnico')], max_length=30, null=True),
        ),
    ]
