# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170126_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tecnico', 'Tecnico'), ('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).')], max_length=30, null=True),
        ),
    ]
