# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20170127_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Tecnico', 'Tecnico')], max_length=30, null=True),
        ),
    ]
