# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20170131_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Tecnico', 'Tecnico')], max_length=30, null=True),
        ),
    ]
