# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20170131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Tecnico', 'Tecnico'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).')], max_length=30, null=True),
        ),
    ]
