# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Tecnico', 'Tecnico'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.')], max_length=30, null=True),
        ),
    ]
