# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20170215_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Tec.', 'Tec.')], default='C.', max_length=30),
        ),
    ]
