# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20170215_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cta_bancaria',
            new_name='cuenta_bancaria',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('Dr.', 'Dr.'), ('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.'), ('Mtro(a).', 'Mtro(a).')], default='C.', max_length=30),
        ),
    ]
