# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20170215_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='CLABE',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('Dr.', 'Dr.'), ('T. S. U.', 'T. S. U.'), ('Ing.', 'Ing.'), ('Lic.', 'Lic.')], default='C.', max_length=30),
        ),
    ]
