# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20170215_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Tec.', 'Tec.'), ('Ing.', 'Ing.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.')], default='C.', max_length=30),
        ),
    ]
