# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20170215_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='CLABE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('T. S. U.', 'T. S. U.'), ('Dr.', 'Dr.'), ('Lic.', 'Lic.'), ('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('Ing.', 'Ing.')], default='C.', max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
