# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20170215_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grado_profesional',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Ing.', 'Ing.'), ('Dr.', 'Dr.'), ('Mtro(a).', 'Mtro(a).'), ('Tec.', 'Tec.'), ('T. S. U.', 'T. S. U.')], default='C.', max_length=30),
        ),
    ]
