# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0005_auto_20170126_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecursofinanciero',
            old_name='user',
            new_name='solicitante',
        ),
    ]
