# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0009_auto_20170126_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30),
        ),
    ]
