# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0010_auto_20170126_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='folio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
