# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0012_auto_20170126_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudrecursofinanciero',
            options={'ordering': ['folio']},
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='solicitante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
