# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0013_auto_20170126_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA'), ('CHEQUE', 'CHEQUE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
