# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0014_auto_20170126_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrecursofinanciero',
            name='cable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
