# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0017_auto_20170127_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudrecursofinanciero',
            old_name='cable',
            new_name='clabe',
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='metodo_pago',
            field=models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('TRANSFERENCIA ELECTRÓNICA', 'TRANSFERENCIA ELECTRÓNICA')], max_length=30),
        ),
    ]
