# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0022_auto_20170131_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='a_nombre_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
