# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursosFinancieros', '0025_auto_20170131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudrecursofinanciero',
            name='a_nombre_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_nombre_de', to=settings.AUTH_USER_MODEL),
        ),
    ]
