# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('monto_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_ampliacion', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monto_reduccion', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monto_ejercido', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monto_modificado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monto_por_ejercer', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('monto_anual_autorizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPresupuestal2.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('actividad', models.TextField()),
                ('meta', models.IntegerField()),
                ('unidad_de_medida', models.CharField(max_length=50)),
                ('fuente_de_financiamiento', models.IntegerField(choices=[(1, 'Federal'), (2, 'Estatal'), (3, 'Propios')])),
                ('beneficiarios', models.TextField()),
                ('oficio_de_autorizacion', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='mes',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPresupuestal2.Partida'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPresupuestal2.Programa'),
        ),
    ]
