# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='monto_modificado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
