# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
