# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0002_auto_20161115_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes',
            old_name='monto_amplicacion',
            new_name='monto_ampliacion',
        ),
    ]
