# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0002_auto_20161118_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPresupuestal2.Programa'),
        ),
    ]
