# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0002_auto_20161117_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='monto_por_ejercer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mes',
            name='monto_modificado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
