# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPresupuestal2', '0003_auto_20161115_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='mes',
            field=models.IntegerField(),
        ),
    ]
